// ============================================================
// WEARWYZER — product / affiliate data
//
// CONTENT INTEGRITY RULES:
// - price: null until a real price is confirmed. The UI shows "Price TBD".
//   When you confirm a price, set price (number) + priceStatus: "confirmed"
//   and update lastChecked.
// - affiliateUrl: "" until a real affiliate link exists. The UI shows a
//   "link pending" state instead of a fake link.
// - brand: "" means "any comparable brand works" (Similar option items).
// ============================================================
export const products = [
  {
    id: "on-cloud-x4",
    name: "On Cloud X 4",
    brand: "On",
    category: "Sneakers",
    colorway: "Ivory / Black",
    image: "assets/images/products/on-cloud-x4.png",
    price: null,
    priceStatus: "tbd", // "tbd" | "confirmed"
    retailer: "", // TODO: e.g. "On.com" once the affiliate program is set up
    affiliateUrl: "", // TODO: paste affiliate link
    exactOrSimilar: "Exact item",
    tags: ["Business casual", "Everyday", "Date night", "Travel", "Gym-to-street"],
    featuredInGuides: ["on-cloud-x4"],
    lastChecked: "", // TODO: set date when price/availability is verified
    // Extended profile for the Featured Products page:
    profile: {
      type: "Athletic lifestyle trainer",
      whyPeopleAsk:
        "It's a running-brand shoe in a clean colorway — guys buy it for the gym, then wonder if they can wear it everywhere else. (They can.)",
      bestFor: ["Casual", "Travel", "Gym-to-street", "Smart casual"],
      stylingDifficulty: "Medium",
      worksWith: ["Chinos", "Tech pants", "Light denim", "Black trousers"],
      avoid: ["Overly formal suits", "Loud clashing colors"],
      alternatives: ["light-jeans"], // TODO: add real alternative shoe IDs as they're covered
    },
  },
  {
    id: "oxford-shirt",
    name: "Light Blue Oxford Shirt",
    brand: "",
    category: "Shirts",
    colorway: "Light blue",
    image: "assets/images/products/oxford-shirt.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Business casual", "Work", "Date night"],
    featuredInGuides: ["on-cloud-x4", "barrel-pants-nb530"],
    lastChecked: "",
  },
  {
    id: "beige-chinos",
    name: "Beige Chinos",
    brand: "",
    category: "Pants",
    colorway: "Beige",
    image: "assets/images/products/beige-chinos.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Business casual", "Work", "Everyday"],
    featuredInGuides: ["on-cloud-x4"],
    lastChecked: "",
  },
  {
    id: "cream-tee",
    name: "Oversized Cream Tee",
    brand: "",
    category: "Shirts",
    colorway: "Cream",
    image: "assets/images/products/cream-tee.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Everyday", "College", "Summer"],
    featuredInGuides: ["on-cloud-x4"],
    lastChecked: "",
  },
  {
    id: "light-jeans",
    name: "Light Wash Jeans",
    brand: "",
    category: "Pants",
    colorway: "Light wash",
    image: "assets/images/products/light-jeans.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Everyday", "College", "Date night"],
    featuredInGuides: ["on-cloud-x4"],
    lastChecked: "",
  },
  {
    id: "cap",
    name: "Neutral Cap",
    brand: "",
    category: "Accessories",
    colorway: "Neutral",
    image: "assets/images/products/cap.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Everyday", "Summer", "College"],
    featuredInGuides: ["on-cloud-x4", "barrel-pants-nb530"],
    lastChecked: "",
  },
  {
    id: "knit-polo",
    name: "Black Knit Polo",
    brand: "",
    category: "Shirts",
    colorway: "Black",
    image: "assets/images/products/knit-polo.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Date night", "Business casual", "Summer"],
    featuredInGuides: ["on-cloud-x4"],
    lastChecked: "",
  },
  {
    id: "black-trousers",
    name: "Black Tailored Trousers",
    brand: "",
    category: "Pants",
    colorway: "Black",
    image: "assets/images/products/black-trousers.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Date night", "Business casual", "Work"],
    featuredInGuides: ["on-cloud-x4"],
    lastChecked: "",
  },
  {
    id: "minimal-watch",
    name: "Minimal Watch",
    brand: "",
    category: "Watches",
    colorway: "Silver / leather",
    image: "assets/images/products/minimal-watch.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Business casual", "Date night", "Work"],
    featuredInGuides: ["on-cloud-x4", "barrel-pants-nb530", "nb9060-zara-polo"],
    lastChecked: "",
  },
  {
    id: "gray-hoodie",
    name: "Gray Hoodie",
    brand: "",
    category: "Hoodies",
    colorway: "Gray",
    image: "assets/images/products/gray-hoodie.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Travel", "Everyday", "College"],
    featuredInGuides: ["on-cloud-x4"],
    lastChecked: "",
  },
  {
    id: "tech-pants",
    name: "Black Tech Pants",
    brand: "",
    category: "Pants",
    colorway: "Black",
    image: "assets/images/products/tech-pants.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Travel", "Everyday", "Gym-to-street"],
    featuredInGuides: ["on-cloud-x4"],
    lastChecked: "",
  },
  {
    id: "backpack",
    name: "Minimal Backpack",
    brand: "",
    category: "Bags",
    colorway: "Black",
    image: "assets/images/products/backpack.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Travel", "College", "Everyday"],
    featuredInGuides: ["on-cloud-x4"],
    lastChecked: "",
  },

  // ---- Guide #2: Zara Hemp Cotton Knit Polo x New Balance 9060 ----
  {
    id: "nb-9060-breakfast-tea",
    name: "New Balance 9060 'Breakfast Tea with Angora'",
    brand: "New Balance",
    category: "Sneakers",
    colorway: "Breakfast Tea",
    image: "assets/images/products/nb-9060-breakfast-tea.png",
    price: 159.99,
    priceStatus: "confirmed",
    retailer: "New Balance",
    affiliateUrl: "", // TODO: paste affiliate link
    exactOrSimilar: "Exact item",
    tags: ["Summer", "Everyday", "Date night", "College", "Travel"],
    featuredInGuides: ["nb9060-zara-polo"],
    lastChecked: "2026-07-09",
    profile: {
      type: "Retro-runner lifestyle sneaker",
      whyPeopleAsk:
        "The 'Breakfast Tea' colorway blew up online — guys own the shoe and want to know what to build around its brown and cream palette.",
      bestFor: ["Summer", "Everyday", "Date night", "Travel"],
      stylingDifficulty: "Medium",
      worksWith: ["Linen shorts", "Wide-leg pants", "Light denim", "Black trousers"],
      avoid: ["Cold-tone grays", "Bright, saturated colors"],
      alternatives: [],
    },
  },
  {
    id: "zara-knit-polo-brown",
    name: "Hemp Cotton Blend Knit Polo",
    brand: "Zara",
    category: "Shirts",
    colorway: "Brown",
    image: "assets/images/products/zara-knit-polo-brown.png",
    price: 79.90,
    priceStatus: "confirmed",
    retailer: "Zara",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Summer", "Date night", "Everyday", "College"],
    featuredInGuides: ["nb9060-zara-polo", "barrel-pants-nb530"],
    lastChecked: "2026-07-09",
  },
  {
    id: "hm-linen-shorts",
    name: "Linen Blend Shorts",
    brand: "H&M",
    category: "Pants",
    colorway: "Natural",
    image: "assets/images/products/hm-linen-shorts.png",
    price: 24.99,
    priceStatus: "confirmed",
    retailer: "H&M",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Summer", "Travel"],
    featuredInGuides: ["nb9060-zara-polo"],
    lastChecked: "2026-07-09",
  },
  {
    id: "af-pleated-shorts",
    name: "Pleated Shorts",
    brand: "Abercrombie & Fitch",
    category: "Pants",
    colorway: "Navy",
    image: "assets/images/products/af-pleated-shorts.png",
    price: 49.95,
    priceStatus: "confirmed",
    retailer: "Abercrombie & Fitch",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["College", "Everyday", "Summer"],
    featuredInGuides: ["nb9060-zara-polo"],
    lastChecked: "2026-07-09",
  },
  {
    id: "cos-wide-leg-pants",
    name: "Wide Leg Pants",
    brand: "COS",
    category: "Pants",
    colorway: "Off White",
    image: "assets/images/products/cos-wide-leg-pants.png",
    price: 115.00,
    priceStatus: "confirmed",
    retailer: "COS",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Everyday", "Date night"],
    featuredInGuides: ["nb9060-zara-polo"],
    lastChecked: "2026-07-09",
  },
  {
    id: "md-black-trousers",
    name: "Tailored Trousers",
    brand: "Massimo Dutti",
    category: "Pants",
    colorway: "Black",
    image: "assets/images/products/md-black-trousers.png",
    price: 129.00,
    priceStatus: "confirmed",
    retailer: "Massimo Dutti",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Date night", "Business casual"],
    featuredInGuides: ["nb9060-zara-polo"],
    lastChecked: "2026-07-09",
  },
  {
    id: "levis-568-jeans",
    name: "568\u2122 Loose Jeans",
    brand: "Levi's",
    category: "Pants",
    colorway: "Light Wash",
    image: "assets/images/products/levis-568-jeans.png",
    price: 69.90,
    priceStatus: "confirmed",
    retailer: "Levi's",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Everyday", "College"],
    featuredInGuides: ["nb9060-zara-polo"],
    lastChecked: "2026-07-09",
  },
  {
    id: "gap-overshirt-beige",
    name: "Lightweight Overshirt",
    brand: "Gap",
    category: "Outerwear",
    colorway: "Beige",
    image: "assets/images/products/gap-overshirt-beige.png",
    price: 59.95,
    priceStatus: "confirmed",
    retailer: "Gap",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Everyday", "Travel"],
    featuredInGuides: ["nb9060-zara-polo"],
    lastChecked: "2026-07-09",
  },
  {
    id: "uniqlo-crossbody-black",
    name: "Crossbody Bag",
    brand: "Uniqlo",
    category: "Bags",
    colorway: "Black",
    image: "assets/images/products/uniqlo-crossbody-black.png",
    price: 19.90,
    priceStatus: "confirmed",
    retailer: "Uniqlo",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Everyday", "Travel"],
    featuredInGuides: ["nb9060-zara-polo"],
    lastChecked: "2026-07-09",
  },
  {
    id: "cos-tote-bag",
    name: "Canvas Tote Bag",
    brand: "COS",
    category: "Bags",
    colorway: "Natural",
    image: "assets/images/products/cos-tote-bag.png",
    price: 45.00,
    priceStatus: "confirmed",
    retailer: "COS",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Summer", "Travel", "Everyday"],
    featuredInGuides: ["nb9060-zara-polo"],
    lastChecked: "2026-07-09",
  },
  {
    id: "mango-sunglasses",
    name: "Round Sunglasses",
    brand: "Mango Man",
    category: "Accessories",
    colorway: "Brown",
    image: "assets/images/products/mango-sunglasses.png",
    price: 49.99,
    priceStatus: "confirmed",
    retailer: "Mango Man",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Summer", "Everyday"],
    featuredInGuides: ["nb9060-zara-polo"],
    lastChecked: "2026-07-09",
  },
  {
    id: "mango-belt-brown",
    name: "Leather Belt",
    brand: "Mango Man",
    category: "Accessories",
    colorway: "Brown",
    image: "assets/images/products/mango-belt-brown.png",
    price: 39.90,
    priceStatus: "confirmed",
    retailer: "Mango Man",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Date night", "Business casual"],
    featuredInGuides: ["nb9060-zara-polo", "barrel-pants-nb530"],
    lastChecked: "2026-07-09",
  },
  {
    id: "gap-crew-socks",
    name: "Crew Socks",
    brand: "Gap",
    category: "Accessories",
    colorway: "White",
    image: "assets/images/products/gap-crew-socks.png",
    price: 9.99,
    priceStatus: "confirmed",
    retailer: "Gap",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Everyday", "College"],
    featuredInGuides: ["nb9060-zara-polo"],
    lastChecked: "2026-07-09",
  },

  // ---- Guide #3: Barrel Pants x New Balance 530 "Turtledove" ----
  {
    id: "nb-530-turtledove",
    name: "New Balance 530 'Turtledove'",
    brand: "New Balance",
    category: "Sneakers",
    colorway: "Turtledove — Angora / Mushroom",
    image: "assets/images/products/nb-530-turtledove.png",
    price: null,
    priceStatus: "tbd",
    retailer: "New Balance",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Everyday", "Summer", "College", "Date night"],
    featuredInGuides: ["barrel-pants-nb530"],
    lastChecked: "",
    profile: {
      type: "Retro-runner lifestyle sneaker",
      whyPeopleAsk:
        "The 530 is a quiet, neutral-toned staple — guys own it and want outfits that don't just repeat the same pair of jeans every time.",
      bestFor: ["Everyday", "Summer", "College", "Date night"],
      stylingDifficulty: "Easy",
      worksWith: ["Wide-leg pants", "Oxford shirts", "Knitwear", "Light denim"],
      avoid: ["Overly bright colors", "Athletic-only styling"],
      alternatives: [],
    },
  },
  {
    id: "uniqlo-barrel-pants-brown",
    name: "Barrel Pants",
    brand: "Uniqlo",
    category: "Pants",
    colorway: "Brown",
    image: "assets/images/products/uniqlo-barrel-pants-brown.png",
    price: null,
    priceStatus: "tbd",
    retailer: "Uniqlo",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Everyday", "Summer", "Date night"],
    featuredInGuides: ["barrel-pants-nb530"],
    lastChecked: "",
  },
  {
    id: "uniqlo-barrel-pants-cream",
    name: "Barrel Pants",
    brand: "Uniqlo",
    category: "Pants",
    colorway: "Cream",
    image: "assets/images/products/uniqlo-barrel-pants-cream.png",
    price: null,
    priceStatus: "tbd",
    retailer: "Uniqlo",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["College", "Everyday"],
    featuredInGuides: ["barrel-pants-nb530"],
    lastChecked: "",
  },
  {
    id: "uniqlo-airism-tee-gray",
    name: "AIRism Oversized T-Shirt",
    brand: "Uniqlo",
    category: "Shirts",
    colorway: "Gray",
    image: "assets/images/products/uniqlo-airism-tee-gray.png",
    price: null,
    priceStatus: "tbd",
    retailer: "Uniqlo",
    affiliateUrl: "",
    exactOrSimilar: "Exact item",
    tags: ["Summer", "Everyday"],
    featuredInGuides: ["barrel-pants-nb530"],
    lastChecked: "",
  },
  {
    id: "ivory-knit-polo",
    name: "Ivory Knit Polo",
    brand: "",
    category: "Shirts",
    colorway: "Ivory",
    image: "assets/images/products/ivory-knit-polo.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Date night", "Everyday"],
    featuredInGuides: ["barrel-pants-nb530"],
    lastChecked: "",
  },
  {
    id: "lightweight-henley",
    name: "Lightweight Henley",
    brand: "",
    category: "Shirts",
    colorway: "Natural",
    image: "assets/images/products/lightweight-henley.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Everyday", "Summer"],
    featuredInGuides: ["barrel-pants-nb530"],
    lastChecked: "",
  },
  {
    id: "black-leather-belt",
    name: "Leather Belt",
    brand: "",
    category: "Accessories",
    colorway: "Black",
    image: "assets/images/products/black-leather-belt.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Business casual", "Everyday"],
    featuredInGuides: ["barrel-pants-nb530"],
    lastChecked: "",
  },
  {
    id: "sunglasses-round",
    name: "Round Sunglasses",
    brand: "",
    category: "Accessories",
    colorway: "Tortoise",
    image: "assets/images/products/sunglasses-round.png",
    price: null,
    priceStatus: "tbd",
    retailer: "",
    affiliateUrl: "",
    exactOrSimilar: "Similar option",
    tags: ["Summer", "Everyday"],
    featuredInGuides: ["barrel-pants-nb530"],
    lastChecked: "",
  },
];

export const CATEGORIES = [
  "Sneakers", "Shoes", "Shirts", "Pants", "Outerwear", "Hoodies", "Accessories", "Watches", "Bags",
];

export const OCCASIONS = [
  "Business casual", "Everyday", "Date night", "Travel", "Summer", "College", "Work", "Gym-to-street",
];
